# Generated by Django 5.0.2 on 2024-02-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0002_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test',
            field=models.CharField(max_length=12),
        ),
    ]
