# Generated by Django 5.0.2 on 2024-02-11 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomapp', '0003_alter_test_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
